In [1]:
import numpy as np
import astropy.units as u
import phise

In [ ]:
c1 = phise.Camera(e=100*u.s)
c2 = phise.CameraOld(e=100*u.s)

print(c1.acquire_pixel(ψ=np.array([1+0j,1.0j])))
print(c2.acquire_pixel(ψ=np.array([1+0j,1.0j])))

In [2]:
%%timeit
c1.acquire_pixel(ψ=np.array([1+0j,1.0j]))

1.36 μs ± 69.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [3]:
%%timeit
c2.acquire_pixel(ψ=np.array([1+0j,1.0j]))

6.72 μs ± 324 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [2]:
N2 = np.array([[1,1],[1,-1]])
N4 = np.array([[1,1,0,0],[1,-1,0,0],[0,0,1,1],[0,0,1,-1]])

ψ = np.array([1+0j,1.0j,0j,0j])


In [4]:
%%timeit
N2 @ ψ[:2]
N2 @ ψ[2:]

4.01 μs ± 42.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [7]:
%%timeit
N4 @ ψ

1.82 μs ± 30 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [ ]:
kn = phise.SuperKN(φ=np.zeros(14)*u.nm, σ=np.zeros(14)*u.nm, λ0=1550*u.nm)
phise.superkn.get_output_fields_jit(ψ, kn.φ.value, kn.σ.value, kn.λ0.value, kn.λ0.value, np.array([0,1,2,3,4,5]))

(array([0.5+0.5j, 0.5-0.5j, 0.5-0.5j]),
 array([5.07490473e-17-5.55111512e-17j, 7.07106781e-01+2.77555756e-17j,
        5.07490473e-17-5.55111512e-17j, 7.07106781e-01+2.77555756e-17j,
        3.53553391e-01-3.53553391e-01j, 3.53553391e-01-3.53553391e-01j]),
 (0.4999999999999999+0.4999999999999999j))

In [4]:
φ = kn.φ.value
σ = kn.σ.value
λ0 = kn.λ0.value
output_order = np.array([0,1,2,3,4,5])

In [ ]:
%%timeit
phise.superkn.get_output_fields_jit(ψ, φ, σ, λ0, λ0, output_order)


6.79 μs ± 137 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [19]:
Y = 1/np.sqrt(2) * np.array([[0.5, 0],[0.5, 0]])
Y@Y.conj().T

array([[0.125, 0.125],
       [0.125, 0.125]])

In [11]:
N2@N2.conj().T

array([[2, 0],
       [0, 2]])

In [25]:
θ = np.pi / 4
R = 1/np.sqrt(2) * np.array([
    [np.exp(1j * θ), np.exp(- 1j * θ)],
    [np.exp(- 1j * θ), np.exp(1j * θ)]
])
R @ R.conj().T

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j]])